# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Khalil Abuawad
title: System developer
email: khalil_abuawad@hotmail.com
website: https://khalilabuawad.github.io/
phone: 45280974

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  KhalilAbuawad
linkedin_username: khalil-abuawad

# About Section
# about_title: Profile
about_profile_image: images/profilepic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hei, mitt navn er Khalil, og jeg er en systemutvikler hos Norsk Luftambulanse Teknologi AS. Jeg er en erfaren programvareutvikler og tar stor stolthet i å være et verdsatt lagmedlem med et bredt spekter av ferdigheter og ekspertise. Jeg spesialiserer meg innen React <mark>React</mark>, <mark>Python</mark>, <mark>CSS</mark>, <mark>PHP</mark> and <mark>SQL</mark>, <mark>SCSS</mark>, <mark>taildwindcss</mark>, <mark>db2</mark>, <mark>docker</mark>, <mark>redux</mark>, og <mark>redux-saga</mark>.

  Som en uavhengig og kreativ beslutningstaker er jeg alltid fokusert på å nå målene mine og finne innovative løsninger på problemer. Jeg er lidenskapelig opptatt av å hjelpe mennesker, og jeg tar meg tid til å forstå deres behov og utvikle løsninger som møter disse behovene.

  Som en full-stack systemutvikler er jeg alltid på jakt etter måter å skape løsninger som jeg er stolt av og som gagner så mange mennesker som mulig. Jeg har sluttbrukerne i tankene til enhver tid og arbeider utrettelig for å sikre at arbeidet mitt oppfyller deres behov.

  Min positive og proaktive tilnærming til problemløsning betyr at jeg er svært effektiv og dyktig i arbeidet mitt, og leverer konsekvent resultater av høy kvalitet. Jeg er alltid ivrig etter å lære og ta fatt på nye utfordringer, noe som gjør meg til en verdifull ressurs for ethvert team.

content:
  - title: Prosjekter # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Latsamband web applikasjon
        link_text: 2022 - 2023
        quote: >
          Som hovedprogrammerer for dette prosjektet, presset jeg meg selv til nye høyder av ferdigheter og ekspertise. Jeg var ansvarlig for hele utviklingsprosessen, fra å velge prosjektstakken til å sette den opp og implementere full-stack funksjonalitet. I begynnelsen jobbet jeg på prosjektet alene, men etter hvert som det utviklet seg, samlet jeg et team for å støtte den fortsatte veksten og utviklingen. Som hovedutvikler tok jeg på meg ansvaret for å designe og utvikle tilgangssystemet for applikasjonen. Målet var å sikre at brukerne fikk passende tilgangsnivåer og ble tilbudt personlige nettfunksjoner basert på deres tilgangsrettigheter.
        description: | # this will include new lines to allow paragraphs
          Latsamband er en innovativ tillegg til den eksisterende mobilapplikasjonen, Latsamband, som brukes av NLAs arbeidsstyrke. Denne nettbaserte plattformen tilbyr ansatte et praktisk alternativ til å utføre kjedelige oppgaver på sine mobile enheter. Den gir en omfattende og effektiv oversikt over deres oppgaver og bidrag, og lar dem legge til ytterligere informasjon når det er nødvendig. Applikasjonen inneholder et tilpassbart dashboard, som viser relevant informasjon om deres fremgang og status, inkludert muligheten til å registrere nye oppdrag og endre eksisterende, bla gjennom oppdrag med en personlig visning og melde seg på kurs. Videre hjelper denne applikasjonen ansatte å holde seg på sporet og støtter dem i å følge opp arbeidsdagen ved å gi varsler for nåværende oppgaver.
        
          Client: Norsk Luftambulanse AS
          
          Results: Responsiv, informativ, vakkert design, interaktiv, personlig tilpasset nettapplikasjon.
          
          Contribution: Lagringstedoppsett, stack-oppsett, prosjektoppsett, utviklingsoppsett, produksjonsoppsett, alle komponenter inkludert: flere startside-sider, oversikt over registrerte oppdrag, oppdragsdetaljside, delt visningsalternativ.
          
          Stack: <mark>React</mark><mark>SCSS</mark><mark>Redux</mark><mark>PHP</mark><mark>DB2</mark><mark>Tailwindcss</mark><mark>Webpack</mark><mark>Redux-saga</mark><mark>Prettier</mark><mark>eslint</mark>
      
      - layout: top-middle
        title: Flightcell
        link_text: 2022 - 2023
        quote: >
          Jeg oppnådde en dypere forståelse av Python-programmering etter å ha bygget en TCP/IP-server fra bunnen av. I tillegg fikk jeg innsikt i Docker og dets potensiale for å styrke et prosjekts robusthet ved å muliggjøre selvkonfigurering og autonom drift. Prosjektet lærte meg også mer om dataanalyse for å forbedre datakvaliteten.
        description: | # this will include new lines to allow paragraphs
          Målet med dette prosjektet er å overføre alle nåværende helikopterhendelser, inkludert posisjonsdata og andre hendelser, til en database. For å oppnå dette, benytter prosjektet TCP/IP for å fange meldinger-over-IP som kommer fra DZMx-enheter plassert i helikoptrene. Ved å bruke Docker, er prosjektet automatisert og forsterket for å sikre en problemfri oppsett og drift.

          Client: Norsk Luftambulanse AS

          Results: Svært motstandsdyktig server for datahenting uten vedlikeholdsbehov.

          Contribution: Opprettelse av TCP/IP-Server, Docker container, Api mot Backend og Database tabeller

          Stack: <mark>Python</mark><mark>Docker</mark><mark>PHP</mark><mark>DB2</mark>
      
      - layout: top-middle
        title: Scheduleringsystem
        link_text: 2021 - 2022
        quote: >
          Dette prosjektet var en måte for meg å forbedre mine frontend-ferdigheter på, fordi jeg var ansvarlig for store deler av utviklingen. Jeg var ny i prosessen og det var utfordrende til tider, men jeg hadde muligheten til å jobbe sammen med en erfaren frontend-utvikler som kunne veilede meg i å utvikle mine ferdigheter.
        description: | # this will include new lines to allow paragraphs
          Scheduleringsystemet var en betydelig del av et stort prosjekt som jeg jobbet med som frontend-utvikler og av og til hjalp backend-teamet. Hovedmålet med dette prosjektet var å gi planleggerne et verktøy for tidsplanlegging og en måte å få en oversikt over situasjonen. Dette verktøyet gir planleggerne muligheten til å planlegge oppgaver og ansvarsområder for fagpersoner som piloter, medisinere og redningsspesialister.

          Client: Norsk Luftambulanse Helikopter AS

          Results: Planleggerne får en god oversikt over timeplanen til personalet sitt. De har tilgang til en kalender som gir både detaljert og overordnet bilde av tidsplanen.  

          Contribution: Ukesvisning av vakt, videre utvikling av timeplanvisning med større visningsalternativer, inkludering av ferie- og sykedager, samt mulighet for vaktbytte mellom ansatte. 

          Frotend stack: <mark>Preact</mark><mark>Sass</mark><mark>Redux</mark><mark>PHP</mark>      
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Norwegian Air Ambulance Technology AS
        link: https://norskluftambulanse.no/
        # link_text: boringcompany.com
        sub_title: System developer
        caption: April 2020 - Present
        quote: >
          The Norwegian Air Ambulance works to ensure that everyone who is acutely ill and seriously injured receives faster and more accurate medical help, no matter where in Norway they are
        description: | # this will include new lines to allow paragraphs
            I have been working on multiple projects and tasks for both inhouse and sister companies. I worked on a range of full stack tasks to data processing and retrieval to further develop new applications used by Norwegian Air Ambulance personnel. 
            
            <mark>React</mark> <mark>Preact</mark> <mark>PHP</mark> <mark>IBM DB2</mark> <mark>JavaScript</mark> <mark>Python</mark> <mark>HTML</mark> <mark>CSS</mark> <mark>Tailwindcss</mark> <mark>Redux</mark> <mark>SQL</mark>
      # The main objective of this project was to give the planners a scheduling tool, but also have a great overview of the scheduling situation. This tool gives the planners the ability to plan the schedule for all the pilots, medics and pararescuers, and much more.
      - layout: left
        title: Symantec AS
        link: https://securitycloud.symantec.com/cc/landing
        # link_text: boringcompany.com
        sub_title: Computer software engineer 
        caption: June 2017 - September 2019
        quote: >
          The company provides cybersecurity software and services.
        description: | # this will include new lines to allow paragraphs
            I was assigned as a frontend developer for their web application used by their analytical team. 
            
            <mark>React</mark> <mark>Go</mark> <mark>Redux</mark> <mark>Python</mark> 
       
      - layout: left
        title: iMerciv Inc
        link: https://www.imerciv.com/
        # link_text: boringcompany.com
        sub_title: Frontend developer
        caption: June 2018 - August 2018
        quote: >
          Merciv caters to the orientation & mobility needs of blind, deaf-blind and visually impaired communities around the globe.
        description: | # this will include new lines to allow paragraphs
            Working as part of the frontend team on a new project in Toronto was an incredible experience that pushed me to new heights of skill and expertise. It was thrilling to be immersed in the startup environment of the city, which has been called the "new Silicon Valley." The speed of the industry there was intense, and I loved every moment of it.

            Our project was to develop a mobile application in React Native that was tailored to the needs of people with disabilities, with a focus on assisting them in travel, much like Google Maps. Our approach relied on the community to mark and post information about obstacles, such as benches. I was fortunate enough to work alongside experienced developers, including an accomplished UX designer and a blind accessibility expert, which helped me to gain a deeper understanding of programming with accessibility, usability, and inclusion in mind.

            During my time there, we were working towards creating a MVP that we could showcase to potential investors. We were successful in our efforts, and we celebrated by going to a Kevin Hart live show! Overall, my experience in Toronto was unforgettable and taught me so much about the industry and the importance of designing with diversity and inclusion in mind.
            
            <mark>React Native</mark>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Masters degree in Informatics programming and system architecture 
        caption: 2019
        sub_title: University of Oslo
        quote: >
          Established in 1811, UiO is the oldest higher education institution in Norway, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in the Nordic countries.
        description: | # this will include new lines to allow paragraphs
          My study towards a Master's Degree ranged across a broad spectrum, taking upon a variety of subjects which directed me towards Gründerskolen. This then enabled me to attend a three month internship in Toronto in where I experienced the fast pace industry of startups. This experienced allowed me to develop both professionally and personally. Whilst taking my masters, I was intrigued by a subject called "Machine Learning and Renewable Energy" which inspired my master thesis: Machine Learning Prediction of Power Demand for Electrical Vehicle Charging Stations in Norway. Thorough research in my Master's degree taught me a lot about data processing and analysis within machine learning. Coming from a programming background I was not expecting machine learning to consist of so much data processing and analysis. I enjoyed programming and experimenting with different machine learning techniques in python.
      - layout: left
        title: Bachelors degree in Informatics programming and system architecture
        caption: 2016
        sub_title: University of Oslo
        quote: >
          Established in 1811, UiO is the oldest higher education institution in Norway, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in the Nordic countries.
        description: | # this will include new lines to allow paragraphs
          The program includes theory and methods for programming both individual machines and machines in networks. One learns to create systems that are reliable, flexible, user-friendly and efficient. Practical solutions to problems are part of the education. One gains insight into the technology behind the computers, how the machine can be used to solve tasks and what challenges the information technology society gives us.
          IT is more than a tool for other subjects. As an computer scientist, we are an active driving force in social development. One works with basic issues that provide new insights and opportunities throughout society, by helping creating new applications.
  
  - title: Courses
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Project leadership (2021)
      - Photography (2020)
  
  - title: Technological proficiency
    layout: text
    content: | # this will include new lines to allow paragraphs
      Methods:
        - Kanban, Project lead, User stories, User testing

      Tools:
        - Jira, Bitbucket, Visual Studio Code, Phpstorm, Datagrip, IBM ACS, Git, Postman, Docker

      Programming language:
        - Javascript, Python, SQL, PHP, HTML, JSON, CSS, SCSS, R

      Framework:
        - React, Preact, Redux, Redux-saga, Tailwindcss, and React Native

      Libraries:
        - Webpack, Vite, Babel

      Cloud:
        - Azure

      Database:
        - DB2
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in system development some of my other interests and hobbies are:
      - Martial arts
      - Calisthenics
      - Drawing/painting
      - Hiking/road trips

# Footer
footer_show_references: true
references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
